enum TokenType {
	LeftParen = 'LeftParen',
	RightParen = 'RightParen',
	LeftBrace = 'LeftBrace',
	RightBrace = 'RightBrace',
	LeftBracket = 'LeftBracket',
	RightBracket = 'RightBracket',
	Comma = 'Comma',
	Dot = 'Dot',
	Semicolon = 'Semicolon',
	Colon = 'Colon',
	Plus = 'Plus',
	Minus = 'Minus',
	Star = 'Star',
	Slash = 'Slash',
	Percent = 'Percent',
	Bang = 'Bang',
	Equal = 'Equal',
	Arrow = 'Arrow',
	EqualEqual = 'EqualEqual',
	BangEqual = 'BangEqual',
	Less = 'Less',
	LessEqual = 'LessEqual',
	Greater = 'Greater',
	GreaterEqual = 'GreaterEqual',
	AndAnd = 'AndAnd',
	OrOr = 'OrOr',
	QuestionQuestion = 'QuestionQuestion',
	QuestionQuestionEqual = 'QuestionQuestionEqual',
	QuestionDot = 'QuestionDot',
	QuestionLeftBracket = 'QuestionLeftBracket',
	PipeGreater = 'PipeGreater',
	Range = 'Range',
	Identifier = 'Identifier',
	Number = 'Number',
	String = 'String',
	Var = 'Var',
	Const = 'Const',
	Fn = 'Fn',
	Constructor = 'Constructor',
	If = 'If',
	Else = 'Else',
	While = 'While',
	For = 'For',
	In = 'In',
	Return = 'Return',
	Import = 'Import',
	Export = 'Export',
	From = 'From',
	Match = 'Match',
	Class = 'Class',
	Extends = 'Extends',
	Public = 'Public',
	Private = 'Private',
	Super = 'Super',
	Break = 'Break',
	Continue = 'Continue',
	Null = 'Null',
	True = 'True',
	False = 'False',
	Then = 'Then',
	Eof = 'Eof',
}

interface Token {
	type: TokenType,
	lexeme: string,
	line: number,
	column: number,
}

const KEYWORDS = new Map<string, TokenType>([
	['var', TokenType.Var],
	['const', TokenType.Const],
	['fn', TokenType.Fn],
	['constructor', TokenType.Constructor],
	['if', TokenType.If],
	['else', TokenType.Else],
	['while', TokenType.While],
	['for', TokenType.For],
	['in', TokenType.In],
	['return', TokenType.Return],
	['import', TokenType.Import],
	['export', TokenType.Export],
	['from', TokenType.From],
	['match', TokenType.Match],
	['class', TokenType.Class],
	['extends', TokenType.Extends],
	['public', TokenType.Public],
	['private', TokenType.Private],
	['super', TokenType.Super],
	['break', TokenType.Break],
	['continue', TokenType.Continue],
	['null', TokenType.Null],
	['true', TokenType.True],
	['false', TokenType.False],
	['then', TokenType.Then],
])

export {
	TokenType,
	Token,
	KEYWORDS,
}
